dist: xenial
language: python
matrix:
  include:
    - python: 3.5
      install:
        - pip install tox-travis
      script:
        - tox
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9
install:
-   pip install tox-travis flake8 black
script:
-   ./pep8.sh
-   tox
